### ISSUE TITLE
[Bug] Failed to decode downloaded font for tim-icons - When deploying to App Engine Server

### ISSUE THREAD

**Issue by MSpaceDev** [creativetimofficial/blk-design-system-angular#7]
### Version
v1.1.0
### Reproduction link
https://celbux-frontend-ng.ew.r.appspot.com/home
(Open console to see errors)
### Operating System
Windows 10
### Device
Dell XPS 13
### Browser & Version
Microsoft Edge 86.0.622.68 [Chromium]
### Steps to reproduce
1. Create and Build the BLK System that uses tim-icons
2. Create an app.yaml next to the generated folder in dist
3. gcloud app deploy to GCP project

4. https://celbux-frontend-ng.ew.r.appspot.com/home
(Open console to see errors)

**APP.YAML CONTENTS**
```
runtime: python27
api_version: 1
threadsafe: true
handlers:

  # Initial route that will serve up index.html, main entry point to your app
  - url: /
    secure: always
    static_files: celbux-frontend-ng/index.html
    upload: celbux-frontend-ng/.*

  # Routing for typedoc, assets and favicon.ico to serve directly
  - url: /((?:assets|docs)/.*|favicon\.ico)
    secure: always
    redirect_http_response_code: 301
    static_files: celbux-frontend-ng/\1
    upload: celbux-frontend-ng/.*

  # Routing for any js files
  - url: /(.*\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: celbux-frontend-ng/\1
    upload: celbux-frontend-ng/.*\.js

  # Routing for any css files
  - url: /(.*\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: celbux-frontend-ng/\1
    mime_type: text/css
    upload: celbux-frontend-ng/.*\.css

  # Routing for anything (wild card) after
  - url: /.*
    secure: always
    static_files: celbux-frontend-ng/index.html
    upload: celbux-frontend-ng/.*

```

### What is expected?
I expect to see the tim-icons show up in my deployed web app
### What is actually happening?
"Failed to decode downloaded font" displayed about x6 times

---
### Solution
I have no solution for this issue.
### Additional comments
I would like assistance to please help me get through this final hurdle.

![image](https://user-images.githubusercontent.com/21283721/99080988-c09bf580-25ca-11eb-82f2-3631d4ffaef9.png)
